local M = {}

local palette = {
	rosewater = "#f5e0dc",
	flamingo = "#f2cdcd",
	pink = "#f5c2e7",
	mauve = "#cba6f7",
	red = "#f38ba8",
	maroon = "#eba0ac",
	peach = "#fab387",
	yellow = "#f9e2af",
	green = "#a6e3a1",
	teal = "#94e2d5",
	sky = "#89dceb",
	sapphire = "#74c7ec",
	blue = "#89b4fa",
	lavender = "#b4befe",
	text = "#cdd6f4",
	subtext1 = "#bac2de",
	subtext0 = "#a6adc8",
	overlay2 = "#9399b2",
	overlay1 = "#7f849c",
	overlay0 = "#6c7086",
	surface2 = "#585b70",
	surface1 = "#45475a",
	surface0 = "#313244",
	base = "#1e1e2e",
	mantle = "#181825",
	crust = "#11111b",
}

M.theme = {
	fg_normal = palette.text,
	bg_normal = palette.base,
	fg_focus = palette.yellow,
	bg_focus = palette.base,
	fg_urgent = palette.red,
	bg_urgent = palette.base,
	bat_fg_critical = palette.red,
	border_normal = palette.lavender,
	border_focus = palette.teal,
	border_marked = palette.red,
	taglist_fg_urgent = palette.base,
	taglist_bg_urgent = palette.red,
	taglist_fg_focus = palette.base,
	taglist_bg_focus = palette.peach,
	taglist_bg_occupied = palette.base,
	taglist_fg_occupied = palette.overlay1,
	taglist_bg_empty = palette.base,
	taglist_fg_empty = palette.surface0,
	tasklist_fg_normal = palette.text,
	icon_theme = "Papirus-Dark",
}

return M
