local dir = os.getenv('HOME') .. '/.config/awesome/theme/icons'

return {
  at = dir .. '/at.svg',
  api = dir .. '/api.svg',
  brightness = dir .. '/brightness-7.svg',
  chart = dir .. '/chart-areaspline.svg',
  chrome = dir .. '/brave.svg',
  close = dir .. '/close.svg',
  code = dir .. '/code-braces.svg',
  folder = dir .. '/folder.svg',
  game = dir .. '/google-controller.svg',
  harddisk = dir .. '/harddisk.svg',
  lab = dir .. '/flask.svg',
  lock = dir .. '/lock.svg',
  logout = dir .. '/logout.svg',
  memory = dir .. '/memory.svg',
  menu = dir .. '/menu.svg',
  music = dir .. '/music.svg',
  plus = dir .. '/plus.svg',
  power = dir .. '/power.svg',
  restart = dir .. '/restart.svg',
  search = dir .. '/magnify.svg',
  slack = dir .. '/slack.svg',
  sleep = dir .. '/power-sleep.svg',
  social = dir .. '/forum.svg',
  thermometer = dir .. '/thermometer.svg',
  volume = dir .. '/volume-high.svg',
  word = dir .. '/word.svg'
}
